# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "62d1114feb88f342f9be3d50be3affe0"
name = "Duxly Connection Hart Beach"
application_url = "https://d7jlhqhgvrgy8.cloudfront.net/?client_id=62d1114feb88f342f9be3d50be3affe0"
embedded = true
handle = "duxly-connection-hart-beach"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  uri = "https://wsrvuo1fz2.execute-api.eu-central-1.amazonaws.com/prod/webhooks/gdpr/customers_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://wsrvuo1fz2.execute-api.eu-central-1.amazonaws.com/prod/webhooks/gdpr/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://wsrvuo1fz2.execute-api.eu-central-1.amazonaws.com/prod/webhooks/gdpr/shop_redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://wsrvuo1fz2.execute-api.eu-central-1.amazonaws.com/prod/callback"
]
